- name: PLAY-1
  hosts: localhost
  tasks:
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug:
      message: Hello i am from paly-1 AND TASK-1

- name: PLAY-2
  hosts: localhost
  tasks:
  - name: PLAY-2 and TASK-2
    ansible.builtin.debug:
      message: Hello i am from play-2 and TASK-2