- name: variables
  hosts: localhost
  vars: #variable declaration
    Course: "Devops" # "" not mandatoty
    Trainer: "Shravan Kumar"
    Duration: "121hrs"

  tasks:
  - name: print information using variables
    ansible.builtin.debug:
      msg: "Hii i am learning {{Course}} from Trainer {{Trainer}} and Duration is {{Duration}}"
