- name: variables
  hosts: localhost
  vars:
    Course: Terraform
    Trainer: Shravan Kumar
    Duration: 121hrs

  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hii i am learning {{Course}} from Trainer {{Trainer}} and Duration is {{Duration}}"
