- name: variables
  hosts: localhost
  vars: # variable declaration
    Course: Devops
    Trainer: shiva kumar
    Duration: 120hrs
  tasks:
  - name: printing overide information
    vars: # Task level variables
      Course: AWS
      Trainer: Shravan
      Duration: 1 month
    ansible.builtin.debug:
      msg: "I am learning {{Course}} from {{Trainer}} and Duration is {{Duration}}"

  - name: printing inheritant information
    ansible.builtin.debug:
      msg: I am learning {{Course}} from {{Trainer}} and Duration is {{Duration}}"
