- name: variables preference
  hosts: localhost
  vars:
    COMPLEMENT: Thank you from play Variable
  var_files:
  - vars.yaml
  vars_prompt:
  - name: COMPLEMENT
    prompt: please enter complement
    private: false
  tasks:
  - name: checking of variable preference
    vars:
      COMPLEMENT: Tank you from TASK variable
    ansible.builtin.debug:
      msg: "Hi shravan {{COMPLEMENT}}"