- name: datatypes
  hosts: Localhost
  vars:
    Course: Devops with AWS # string
    Tools: # list
    - Linux
    - Shell-Script
    - Ansible
    Experience: # map
      Devops: 3
      AWS: 2
      Docker: 1
    Realproject: true # boolean

  tasks:
  - name: 
    ansible.builtin.debug:
      msg: "course: {{Course}}, tools covered: {{Tools}}, experience is: {{Experience}} is realproject:{{Realproject}}"