- name: Demo on Loops # Loop means we can make loop from list of items
  hosts: localhost
 
  tasks:
  - name: loops from list
    ansible.builtin.debug:
      msg: "Hello {{item}}"
    loop:
    - Shell
    - Linux
    - Ansible