- name: Installing packages
  hosts: localhost
  tasks:
  - name: Installing packages
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
    loop:
    - mysql
    - nginx
    - postfix