- name: installing packages
  hosts: localhost
  become: yes
  tasks: 
  - name: installing packages
    ansible.builtin.dnf:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - { name: 'mysql', state: 'latest' } #this is item
    - { name: 'nginx', state: 'absent' }
    - { name: 'postfix', state: 'absent' }